### ISSUE TITLE
LABEL is not properly handled by dockerfile-parse

### ISSUE THREAD

**Issue by phracek** [DBuildService/dockerfile-parse#28]
If Dockerfile is defined like:

~~~
LABEL summary="Postfix is a Mail Transport Agent (MTA)." \
       version = "1.0" \
       description="Postfix is mail transfer agent that routes and delivers mail." \
       io.k8s.description="Postfix is mail transfer agent that routes and delivers mail." \
       io.k8s.display-name="Postfix 3.1" \
       io.openshift.expose-services="10025:postfix" \
io.openshift.tags="postfix,mail,mta"
~~~

then dockerfile-parse parse it like:
~~~
{u'content': u'LABEL summary="Postfix is a Mail Transport Agent (MTA)." \\\n    version="1.0" \\\n    description="Postfix is mail transfer agent that routes and delivers mail." \\\n    io.k8s.description="Postfix is mail transfer agent that routes and delivers mail." \\\n    io.k8s.diplay-name="Postfix 3.1" \\\n    io.openshift.expose-services="10025:postfix" \\\n    io.openshift.tags="postfix,mail,mta"\n',
 u'endline': 22,
 u'instruction': u'LABEL',
 u'startline': 16,
 u'value': u'summary="Postfix is a Mail Transport Agent (MTA)."     version="1.0"     description="Postfix is mail transfer agent that routes and delivers mail."     io.k8s.description="Postfix is mail transfer agent that routes and delivers mail."     io.k8s.diplay-name="Postfix 3.1"     io.openshift.expose-services="10025:postfix"     io.openshift.tags="postfix,mail,mta"'}
~~~

python program as reproducer:
~~~
        dfp = DockerfileParser(path=self.dir)
        import pprint
        for struct in dfp.structure:
            pprint.pprint(struct)
~~~

Would it be possible to somehow structure it?

**Comment by twaugh** [comment]
The `labels` property provides access to individual labels.

**Comment by lcarva** [comment]
Each item in structure is meant to represent an instruction, which can span multiple lines. I'm not sure I understand the request, could you provide example of the behavior you're expecting?

**Comment by phracek** [comment]
Hi folks, I am happy you responded.

If my labels are defined like multiple lines like in my case, I would prefer to create a structure like below.

SEE value. Nowadays it is string, which is wrongly parsable by python.
~~~
{u'content': u'LABEL summary="Postfix is a Mail Transport Agent (MTA)." \\\n    version="1.0" \\\n    description="Postfix is mail transfer agent that routes and delivers mail." \\\n    io.k8s.description="Postfix is mail transfer agent that routes and delivers mail." \\\n    io.k8s.diplay-name="Postfix 3.1" \\\n    io.openshift.expose-services="10025:postfix" \\\n    io.openshift.tags="postfix,mail,mta"\n',
 u'endline': 22,
 u'instruction': u'LABEL',
 u'startline': 16,
 u'value': [u'summary="Postfix is a Mail Transport Agent (MTA)."',
               u'version="1.0"',
               u'description="Postfix is mail transfer agent that routes and delivers mail."',
               u'io.k8s.description="Postfix is mail transfer agent that routes and delivers mail."'
               u'io.k8s.diplay-name="Postfix 3.1"'
               u'io.openshift.expose-services="10025:postfix"',
               u'io.openshift.tags="postfix,mail,mta"'
}

~~~

**Comment by phracek** [comment]
If labels are on separated lines like:
LABEL key1=value1
LABEL key2=value2
then all works fine.

**Comment by twaugh** [comment]
Please see the new `context_structure` property: https://github.com/DBuildService/dockerfile-parse/releases/tag/0.0.7. This provides better support for inspecting labels and environment variables.

**Comment by phracek** [comment]
I have dockerfile-parse-0.0.7 but it tracebacks with

~~~
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/moduleframework/tools/helpmd_lint.py", line 43, in setUp
     self.dp = dockerlinter.DockerfileLinter()
   File "/usr/lib/python2.7/site-packages/moduleframework/dockerlinter.py", line 43, in __init__
     self._get_structure_as_dict()
   File "/usr/lib/python2.7/site-packages/moduleframework/dockerlinter.py", line 93, in _get_structure_as_dict
     print("PRINT LABELS: %s" % self.dfp.labels)
   File "/usr/lib/python2.7/site-packages/dockerfile_parse/parser.py", line 314, in labels
     return self._instruction_getter('LABEL', env_replace=self.env_replace)
   File "/usr/lib/python2.7/site-packages/dockerfile_parse/parser.py", line 344, in _instruction_getter
     for key, value in key_val_list:
 TypeError: 'NoneType' object is not iterable

~~~

Dockerfile which I used is https://github.com/sclorg/postgresql-container/blob/master/9.5/Dockerfile
Reproducer in ipython:
~~~
import dockerfile_parse DockerfileParser
with open('./Dockerfile', "r") as f:
      dfp =DockerfileParser(fileobj=f)
      dfp_structure = dfp.structure
      for label in dfp.labels:
           print(label)

~~~

**Comment by phracek** [comment]
@twaugh After some debugging in line https://github.com/DBuildService/dockerfile-parse/blob/master/dockerfile_parse/parser.py#L341

key_val_list looks like:
~~~
key_val_list [(u'summary', u'PostgreSQL'), None, None, None, None, None, None, None, (u'description', u"PostgreSQL is an advanced Object-Relational database management system (DBMS). The image contains the client and server programs that you'll need to create, run, maintain and access a PostgreSQL DBMS server."), (u'io.k8s.description', u"PostgreSQL is an advanced Object-Relational database management system (DBMS). The image contains the client and server programs that you'll need to create, run, maintain and access a PostgreSQL DBMS server."), (u'io.k8s.display-name', u'PostgreSQL 9.5'), (u'io.openshift.expose-services', u'5432:postgresql'), (u'io.openshift.tags', u'database,postgresql,postgresql95,rh-postgresql95'), (u'name', u'centos/postgresql-95-centos7'), (u'com.redhat.component', u'rh-postgresql95-docker'), (u'version', u'9.5'), (u'usage', u'docker run -d --name postgresql_database -e POSTGRESQL_USER=user -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=db -p 5432:5432 centos/postgresql-95-centos7'), (u'maintainer', u'SoftwareCollections.org <sclorg@redhat.com>')]

~~~

**Comment by TomasTomecek** [comment]
This is the real culprit:
```
LABEL summary=$SUMMARY \
      description="$DESCRIPTION" \
```

`summary` is not quoted and hence is then expanded with `split` like this:
```
['summary=PostgreSQL', 'is', 'an', 'advanced', 'Object-Relational', 'database', 'management', 'system', "description=PostgreSQL is an ad...
```

**Comment by lcarva** [comment]
Fixed by https://github.com/DBuildService/dockerfile-parse/pull/54
